language: rust
rust: nightly

env:
    global:
        - secure: I4WPZjTaIGzkYLG4SfPM5xonXGtJaagWgU9Nodw3+5qNZ4wLWK+hWFU4G4leApDnT0n+2Og6T29/Hbq81DfZFC9uWy5EPXOBcdOD9Ge4Cktap2b1ciPXbK1smq2O0W20Z0kRyvNJ57Hgt7tR4DhE6NrecR+Sp+BUlAyeyv7VG2g=

script:
    - cargo build -v
    - cargo test -v
    - cargo doc

after_script:
    - cd target && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh 
