language: rust
rust: nightly

env:
    global:
        - secure: EUfEQIcFJtMALM7RDe0z3qxyjfxyQQR7qgoyEWSMsXewywrSmpF2JqAwnknOFBhKPxVVqboLugL0g1j+syTdPB2nx7pw2GoN/gAIRdyl6+8zdjeSKqDeMulv+3y3cOp02xv1pz3/3x4jyk9fMSKfl2/2PzNUv6rCZlD0UgMurAg=

script:
    - cargo build -v
    - cargo test -v
    - cargo doc

after_script:
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh 
