[package]
name = "email"
version = "0.0.16"
authors = ["Nicholas Hollett <niax@niax.co.uk>"]
description = "Implementation of RFC 5322 email messages"
repository = "https://github.com/niax/rust-email"
documentation = "https://niax.github.io/rust-email/email/"
license = "MIT"
build = "build.rs"

[dependencies]
encoding = "^0.2.0"
chrono = "^0.3.0"
lazy_static = "^0.2.0"
base64 = "^0.5.0"
rand = "^0.3.0"
time = "^0.1.0"

[features]
nightly = []

[build-dependencies]
rustc_version = "0.1.*"
