[package]

name = "email"
version = "0.0.10"
authors = ["Nicholas Hollett <niax@niax.co.uk>"]
description = "Implementation of RFC 5322 email messages"
repository = "https://github.com/niax/rust-email"
documentation = "https://niax.github.io/rust-email/email/"
license = "MIT"

[dependencies]
encoding = "0.2"
time = "0.1"
chrono = "0.2"
lazy_static = "0.1"
rustc-serialize = "0.3"
rand = "0.3"
