[package]

name = "email"
version = "0.0.8"
authors = ["Nicholas Hollett <niax@niax.co.uk>"]
description = "Implementation of RFC 5322 email messages"
repository = "https://github.com/niax/rust-email"
documentation = "https://niax.github.io/rust-email/email/"
license = "MIT"

[dependencies]
encoding = "~0.2.12"
time = "~0.1.7"
chrono = "~0.1.7"
lazy_static = "~0.1.4"
rustc-serialize = "0.2"
