[package]

name = "email"
version = "0.0.2"
authors = ["Nicholas Hollett <niax@niax.co.uk>"]
description = "Implementation of RFC 5322 email messages"
repository = "https://github.com/niax/rust-email"
documentation = "http://www.rust-ci.org/niax/rust-email/doc/email/"
license = "MIT"

[dependencies]
encoding = "~0.2.3"
